# Generated by Django 4.0.2 on 2022-03-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmarks',
            name='date_attempted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
